apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: {{ template "ingestName" . }}
  labels:
    nuclio.io/project-name: {{ .Values.project.name }}
spec:
  handler: main:Ingest
  image: {{ .Values.ingest.image.repository }}:{{ .Values.ingest.image.repository }}
  replicas: 1
  runtime: golang
  env:
  - name: INGEST_V3IO_TSDB_PATH
    value: {{ .Values.ingest.tsdb.path }}
  dataBindings:
    db0:
      class: v3io
      secret: {{ .Values.ingest.tsdb.username }}:{{ .Values.ingest.tsdb.password }}
      url: {{ .Values.ingest.tsdb.url | quote }} 
status:
  state: waitingForResourceConfiguration
